// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";
import * as __TAURI_EVENT from "@tauri-apps/api/event";

/** Commands */
export const commands = {
	getStatus: () => __TAURI_INVOKE<RuntimeStatus>("get_status"),
	getConfig: () => __TAURI_INVOKE<VblSettings_Serialize>("get_config"),
	updateConfig: (config: VblSettings_Deserialize) => __TAURI_INVOKE<void>("update_config", { config }),
	listProfiles: () => __TAURI_INVOKE<string[]>("list_profiles"),
	activeProfile: () => __TAURI_INVOKE<string>("active_profile"),
	switchProfile: (name: string) => __TAURI_INVOKE<{
	skill: SkillMode,
	macroKeys: MacroKeybinds,
	tapMs: number,
	capture: CaptureState_Serialize[],
	crosshair: CrosshairConfig,
	script: string | null,
	dsl: string | null,
	unfocusedPanicMs: number | null,
	/**  Arm the engine automatically when the app launches. */
	armOnStart: boolean,
} | null>("switch_profile", { name }),
	saveProfileAs: (name: string) => __TAURI_INVOKE<void>("save_profile_as", { name }),
	deleteProfile: (name: string) => __TAURI_INVOKE<{
	skill: SkillMode,
	macroKeys: MacroKeybinds,
	tapMs: number,
	capture: CaptureState_Serialize[],
	crosshair: CrosshairConfig,
	script: string | null,
	dsl: string | null,
	unfocusedPanicMs: number | null,
	/**  Arm the engine automatically when the app launches. */
	armOnStart: boolean,
} | null>("delete_profile", { name }),
	/**  Write the active profile to a JSON file the user picked. */
	exportProfile: (path: string) => typedError<null, string>(__TAURI_INVOKE("export_profile", { path })),
	/**
	 *  Import a profile from a JSON file, validate it, save it under the file's name, make it active,
	 *  and load it into the engine. Returns the imported settings.
	 */
	importProfile: (path: string) => typedError<VblSettings_Serialize, string>(__TAURI_INVOKE("import_profile", { path })),
	/**  Compute a tolerance that matches the `on` color but not the `off` sample (auto-calibration). */
	suggestTolerance: (on: Rgb, off: Rgb) => __TAURI_INVOKE<Tolerance>("suggest_tolerance", { on, off }),
	pickPixel: () => __TAURI_INVOKE<{
	x: number,
	y: number,
	r: number,
	g: number,
	b: number,
} | null>("pick_pixel"),
	sampleCapture: () => __TAURI_INVOKE<CaptureSampleDto_Serialize[]>("sample_capture"),
	recentInjections: () => __TAURI_INVOKE<InjectionDto[]>("recent_injections"),
	getMetrics: () => __TAURI_INVOKE<Metrics>("get_metrics"),
	arm: () => __TAURI_INVOKE<void>("arm"),
	disarm: () => __TAURI_INVOKE<void>("disarm"),
	toggleArmed: () => __TAURI_INVOKE<void>("toggle_armed"),
	reloadScript: () => __TAURI_INVOKE<void>("reload_script"),
};

/** Events */
export const events = {
	logEvent: makeEvent<LogEvent>("log-event"),
	statusEvent: makeEvent<StatusEvent>("status-event"),
};

/* Types */
export type Aggregate = "any" | "majority" | "all";

export type CaptureSampleDto = CaptureSampleDto_Serialize | CaptureSampleDto_Deserialize;

export type CaptureSampleDto_Deserialize = {
	key: StateKey_Deserialize,
	x: number,
	y: number,
	r: number,
	g: number,
	b: number,
	matched: boolean,
};

export type CaptureSampleDto_Serialize = {
	key: StateKey_Serialize,
	x: number,
	y: number,
	r: number,
	g: number,
	b: number,
	matched: boolean,
};

export type CaptureState = CaptureState_Serialize | CaptureState_Deserialize;

export type CaptureState_Deserialize = {
	key: StateKey_Deserialize,
	point: NormalizedPoint,
	target: Rgb,
	tolerance: Tolerance,
	region?: Region,
};

export type CaptureState_Serialize = {
	key: StateKey_Serialize,
	point: NormalizedPoint,
	target: Rgb,
	tolerance: Tolerance,
	region: Region,
};

export type CrosshairConfig = {
	enabled: boolean,
	color: string,
	offset: CrosshairOffset,
	scale: number | null,
	opacity: number | null,
};

export type CrosshairOffset = {
	x: number,
	y: number,
};

export type InjectionDto = {
	tsMs: number,
	label: string,
};

export type LogEntry = {
	id: number,
	kind: LogKind,
	timestampMs: number,
	message: string,
};

export type LogEvent = LogEntry;

export type LogKind = "log" | "error";

export type MacroKeybinds = {
	enabled: boolean,
	jumpsetKey: string,
	skillKey: string,
	toggleUltimateKey: string,
	respawnKey: string,
	killSwitchKey?: string,
};

export type Metrics = {
	captureMicros: number,
	captureP50Micros: number,
	captureP95Micros: number,
	captureMaxMicros: number,
	captureSamples: number,
	injections: number,
	pollCount: number,
};

export type NormalizedPoint = {
	nx: number | null,
	ny: number | null,
};

export type PixelPick = {
	x: number,
	y: number,
	r: number,
	g: number,
	b: number,
};

export type Region = {
	w: number,
	h: number,
};

export type Rgb = {
	r: number,
	g: number,
	b: number,
};

export type RuntimeStatus = {
	armed: boolean,
	targetFocused: boolean,
	captureMatched: boolean,
	gameOnGround: boolean,
	gameUltimateReady: boolean,
	x1Held: boolean,
	x2Held: boolean,
	skillEnabled: boolean,
	resolution: [number, number] | null,
};

export type SkillMode = "normal" | "boomjump";

export type StateKey = StateKey_Serialize | StateKey_Deserialize;

export type StateKey_Deserialize = "GameOnGround" | "GameUltimateReady" | "GameSkillReady" | "X1Held" | "X2Held" | "skillEnabled" | "robloxFocused";

export type StateKey_Serialize = "GameOnGround" | "GameUltimateReady" | "X1Held" | "X2Held" | "skillEnabled" | "robloxFocused";

export type StatusEvent = RuntimeStatus;

export type Tolerance = {
	perChannel: number,
	aggregate?: Aggregate,
};

export type VblSettings = VblSettings_Serialize | VblSettings_Deserialize;

export type VblSettings_Deserialize = {
	skill: SkillMode,
	macroKeys: MacroKeybinds,
	tapMs: number,
	capture: CaptureState_Deserialize[],
	crosshair: CrosshairConfig,
	script?: string | null,
	dsl?: string | null,
	unfocusedPanicMs?: number | null,
	/**  Arm the engine automatically when the app launches. */
	armOnStart?: boolean,
};

export type VblSettings_Serialize = {
	skill: SkillMode,
	macroKeys: MacroKeybinds,
	tapMs: number,
	capture: CaptureState_Serialize[],
	crosshair: CrosshairConfig,
	script: string | null,
	dsl: string | null,
	unfocusedPanicMs: number | null,
	/**  Arm the engine automatically when the app launches. */
	armOnStart: boolean,
};

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

type EventEmit<T> = [T] extends [null] ? () => Promise<void> : (payload: T) => Promise<void>;

function makeEvent<T>(name: string, serialize?: (payload: T) => unknown, deserialize?: (payload: any) => T) {
    const mapEvent = (cb: __TAURI_EVENT.EventCallback<T>) => (event: __TAURI_EVENT.Event<any>) => cb({ ...event, payload: deserialize ? deserialize(event.payload) : event.payload });
    const mapPayload = (payload: T) => serialize ? serialize(payload) : payload;

    const base = {
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.once(name, mapEvent(cb)),
        emit: ((payload: T) => __TAURI_EVENT.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    };

    const fn = (target: import("@tauri-apps/api/webview").Webview | import("@tauri-apps/api/window").Window) => ({
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => target.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => target.once(name, mapEvent(cb)),
        emit: ((payload: T) => target.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    });

    return Object.assign(fn, base);
}

